//Defines
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define V_SCREEN_X 0
#define V_SCREEN_Y 0

#define COLOR_BITS 32
#define VIDEO_CARD GFX_AUTODETECT_WINDOWED

#define DIGI_CARD DIGI_AUTODETECT
#define MIDI_CARD MIDI_AUTODETECT

#define MAX_FPS  50

#define FPS_EXPLOSAO 41
#define FPS_FOGO 26
#define FPS_AGUA 80
#define FPS_TIRO_AGUA 42

// Define dos estados das telas
#define GAME_STATE_INTRO 0
#define GAME_STATE_IN_GAME  1
#define GAME_STATE_INSTRUCTIONS 2
#define GAME_STATE_GAMEOVER  3
#define GAME_STATE_FINISH 4
